server:
  port: 9090
  address: 192.168.0.187
spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

      routes:
        - id : CONSULTATION-SERVICE
          uri: lb://CONSULTATION-SERVICE
          predicates:
            - Path=/consultation/**
          filters:
            - name: CircuitBreaker
              args:
                name: CONSULTATION-SERVICE
                fallbackuri: forward:/consultationServiceFallBack
                #- name: RequestRateLimiter
                #args:
                #redis-rate-limiter.replenishRate: 1
                #redis-rate-limiter.burstCapacity: 1
        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient/**
          filters:
            - name: CircuitBreaker
              args:
                name: PATIENT-SERVICE
                fallbackuri: forward:/patientServiceFallBack
                #- name: RequestRateLimiter
                #args:
                #redis-rate-limiter.replenishRate: 1
                #redis-rate-limiter.burstCapacity: 1
        - id: DOCTOR-SERVICE
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctor/**
          filters:
            - name: CircuitBreaker
              args:
                name: DOCTOR-SERVICE
                fallbackuri: forward:/doctorServiceFallBack
                #- name: RequestRateLimiter
                #args:
                #redis-rate-limiter.replenishRate: 1
                #redis-rate-limiter.burstCapacity: 1
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}